
// Objective-C API for talking to the following Go packages
//
//	sample-app/demo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Demo_FRAMEWORK_H__
#define __Demo_FRAMEWORK_H__

#include "Demo.objc.h"
#include "Universe.objc.h"

#endif
