// Objective-C API for talking to sample-app/demo Go package.
//   gobind -lang=objc sample-app/demo
//
// File is generated by gobind. Do not edit.

#ifndef __Demo_H__
#define __Demo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull DemoSayHi(NSString* _Nullable text);

#endif
